services:
  - type: web
    name: rock-paper-scissors
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT